services:
  limitation-db:
    image: postgres:latest
    container_name: limitation-db
    restart: unless-stopped

    ports:
      - "5435:5432"

    environment:
      POSTGRES_DB: limitation-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - limitation-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d limitation-db"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  limitation-db-data:
